apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-api-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JadynStoltz/argocd-python-api-config.git
    targetRevision: main
    path: python-api
  destination:
    server: https://kubernetes.default.svc
    namespace: python-api

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true