apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  selector:
    matchLabels:
      app: python-api
  replicas: 2
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: docker.io/stoltzjadyn/examplenode-dev:9
          ports:
            - containerPort: 8000
