name: Repository Dispatch

on:
  repository_dispatch:
    types: [new-image]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Image Version
        id: imgupd
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i python-api/deployment.yaml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply image name changes
